### PR TITLE
fix for libjpeg in makemWin.js

### PR DESCRIPTION
**Pull request by kalwalt**
This should fix the build, let me know!
- [x] changes in path for libjpeg in the` makemWin.js `script.

### CODE REVIEW

**Comment by kalwalt** [comment]
In the readme you wrote:

`5. In the emcc env, run "node tools/makem.js".`

but usually i run "npm run build"  but of course if you have a makemWin.js script you can change the command in the package.json here: https://github.com/Carnaux/NFT-Marker-Creator/blob/04177a852a0408648cc849039440ccf77ee3b24d/nft/package.json#L38
or run the command directly with node.

Also i saw that in jsartoolkit5 there is a `.npmignore` file https://github.com/artoolkitx/jsartoolkit5/blob/master/.npmignore not sure that is revelant but maybe we neeed to add?

**Comment by kalwalt** [comment]
I found a similar issue in the jsartoolkit5 issue tracker, https://github.com/artoolkitx/jsartoolkit5/issues/31
it is related to windows path, so i think not many people tryied to build the jsartoolkit5 lib under Windows OS. Because the build script of this project is based on the jsartoolkit5 setup, we can solve also this other issue. :smile:

**Comment by Carnaux** [comment]
> In the readme you wrote:
> 
> `5. In the emcc env, run "node tools/makem.js".`
> 
> but usually i run "npm run build" but of course if you have a makemWin.js script you can change the command in the package.json here:
> 
> https://github.com/Carnaux/NFT-Marker-Creator/blob/04177a852a0408648cc849039440ccf77ee3b24d/nft/package.json#L38
> 
> 
> or run the command directly with node.
> Also i saw that in jsartoolkit5 there is a `.npmignore` file https://github.com/artoolkitx/jsartoolkit5/blob/master/.npmignore not sure that is revelant but maybe we neeed to add?

Yeah, i think we need to add it. Maybe it is to avoid conflict.

**Comment by Carnaux** [comment]
> I found a similar issue in the jsartoolkit5 issue tracker, [artoolkitx/jsartoolkit5#31](https://github.com/artoolkitx/jsartoolkit5/issues/31)
> it is related to windows path, so i think not many people tryied to build the jsartoolkit5 lib under Windows OS. Because the build script of this project is based on the jsartoolkit5 setup, We can solve also this other issue. 😄

Nice!!! 🎉

**Pull request merged**
