### PR TITLE
Adding web version and enhanced UI (responsiveness, design)

### PR DESCRIPTION
**Pull request by nicolocarpignoli**
solve #24

### CODE REVIEW

**Comment by nicolocarpignoli** [comment]
can someone please test if now with these modifies, web version is better (and still works) and also node version still works?

**Comment by kalwalt** [comment]
@nicolocarpignoli I will test this!

**Comment by kalwalt** [comment]
Testing the node app i receive this error:

```shell
walter@walter-RC530-RC730:~/kalwalt-github/NFT-Marker-Creator$ node app.js
/home/walter/kalwalt-github/NFT-Marker-Creator/NftMarkerCreator.min.js:1
var Module=typeof Module!=="undefined"?Module:{};var moduleOverrides={};var key;for(key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var arguments_=[];var thisProgram="./this.program";var quit_=function(status,toThrow){throw toThrow};var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_HAS_NODE=false;var ENVIRONMENT_IS_SHELL=false;ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_HAS_NODE=typeof process==="object"&&typeof process.versions==="object"&&typeof process.versions.node==="string";ENVIRONMENT_IS_NODE=ENVIRONMENT_HAS_NODE&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(Module["ENVIRONMENT"]){throw new Error("Module.ENVIRONMENT has been deprecated. To force the environment, use the ENVIRONMENT compi

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:113:11)
    at Object.basename (path.js:1156:5)
    at Object.<anonymous> (/home/walter/kalwalt-github/NFT-Marker-Creator/app.js:13:28)
    at Module._compile (internal/modules/cjs/loader.js:1121:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1160:10)
    at Module.load (internal/modules/cjs/loader.js:976:32)
    at Function.Module._load (internal/modules/cjs/loader.js:884:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:67:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'ERR_INVALID_ARG_TYPE'
}

```

i deleted **node_modules** and re-installed all the dependencies with npm install and i get the same result.

**Comment by nicolocarpignoli** [comment]
Have you added one image inside the input folder?

**Comment by kalwalt** [comment]
No i will try to add.

**Comment by kalwalt** [comment]
@nicolocarpignoli there is not a input folder, i will create a new one.

**Comment by kalwalt** [comment]
Yes that was te cause! It would be better to improve the error handling, in case the path is missed.

**Comment by kalwalt** [comment]
Schermata da 2020-01-08 13-41-36
This is on desktop with the web version i'm generating the nft marker, You can see in the log console all the process. It is not necessary give any input.

**Comment by kalwalt** [comment]
The nft marker set for the pinball.jpg was generated succesfully. Some details:

```js
NftMarkerCreator.min.js:1 [info] Generator started at 2020-01-08 13:42:56 +0100
NftMarkerCreator.min.js:1 [info] Generator finished at 2020-01-08 13:53:31 +0100
```
time to complete the task around 10 minutes not bad for the web version!

**Comment by nicolocarpignoli** [comment]
@kalwalt the error message when missing input image should be necessary only for node version. Yes it needs improvement, at least when finding such problem, then Log something like 'Please provide one, and only one image on the "input" folder)'.

Anyway, speed of the web version is depending also on machine power. I got only few minutes with an image similar to pinball one, talking about size. Anyway, I agree, it's pretty good for the web version that will not act, in my opinion, as the default interface.

**Comment by nicolocarpignoli** [comment]
What's important for this PR is also the loader, and the responsiveness (try to resize the window, should be visible the same way or so, and should be usable).

**Comment by kalwalt** [comment]
> @kalwalt the error message when missing input image should be necessary only for node version. Yes it needs improvement, at least when finding such problem, then Log something like 'Please provide one, and only one image on the "input" folder)'.

yes that was my idea!

> Anyway, speed of the web version is depending also on machine power. I got only few minutes with an image similar to pinball one, talking about size. Anyway, I agree, it's pretty good for the web version that will not act, in my opinion, as the default interface.

talking about benchmark: it would be nice to have a total time for generating the feature set. 

> What's important for this PR is also the loader, and the responsiveness (try to resize the window, should be visible the same way or so, and should be usable).

i will do, i'm testing that the node app.js waiting that finish the process...

**Comment by kalwalt** [comment]
This is the time for the node app.js to finish the task 
```
[info] Generator started at 2020-01-08 13:59:11 +0100

[info] Generator finished at 2020-01-08 14:09:42 +0100

```

there is no such big difference with the web version, at least for me. I'm testing with a desktop PC (ubuntu 18.04 LTS).

**Comment by nicolocarpignoli** [comment]
my performances tests:

on Desktop (Macbook pro, Chrome 79)

```
WEB:
Generator started at 2020-01-08 15:16:43 +0100
Generator finished at 2020-01-08 15:24:21 +0100

NODE:
Generator started at 2020-01-08 15:30:27 +0100
Generator finished at 2020-01-08 15:37:18 +0100
```
So I confirm, as for speed times, Web version is practically the same as Node version. This is good!

Keep in mind that those images are pretty big (as resolution, at least). Performance are far better with lower resolutions (I got something like 5/10 seconds for some images, even less).

**Comment by nicolocarpignoli** [comment]
@Carnaux I think that with this PR and another one enhancing the node version, we have reached a very good, stable version of the NFT marker :D In my opinion it can be delivered and used with AR.js as soon as that will be ready.

**Comment by kalwalt** [comment]
Not related to this PR, but does make sense to add also width, height, dpi options in the web version in your opinion?

**Comment by nicolocarpignoli** [comment]
Yes, could be. We can open a separate issue for that and see in the future if/when implementing.

**Comment by Carnaux** [comment]
Nice!! Thanks!! I'm traveling now, so I won't be able to implement some changes in a couple of days, but I already planned adding a command options in the web version, like the node cmd lines. The .c code accept a lot more of configurations than is implemented, extraction levels, precision, max and min dpi and so on. But these configurations are optional, for general use it will be as today.

**Pull request merged**
