### PR TITLE
Adding emscripten USE_LIBJPEG flag and simplifiyng the build

### PR DESCRIPTION
**Pull request by kalwalt**
As noted in this issue https://github.com/Carnaux/NFT-Marker-Creator/issues/21 by emscripten **v1.38.31** libjpeg can be included in the project simply adding the flag **USE_LIBJPEG**.
This PR add that flag in makem.js and apply other changes accordingly.
This PR make a bit easier the project setup.

### CODE REVIEW

**Comment by kalwalt** [comment]
@Carnaux What is the pourpose of https://github.com/Carnaux/NFT-Marker-Creator/blob/dev/genTexData%20-%20Copia.c ? May we delete it?

**Comment by Carnaux** [comment]
Yes, It was just a backup. Thanks!!!

**Comment by kalwalt** [comment]
ok i will delete it and i will also update the README.md (deleting the libjpeg point where was necessary to download the libjpeg lib)

**Comment by kalwalt** [comment]
@Carnaux i'm fine with it, test it if you have time. I used  emcc **1.39.5** (fastcomp) to build the project.

**Comment by Carnaux** [comment]
It works!

**Comment by kalwalt** [comment]
ok happy for this! i will update also the master branch with the newest lib if you want, even if shouldn't be such great differences.

**Pull request merged**
